# Generated by Django 4.2.2 on 2023-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
            ],
        ),
    ]
