# Generated by Django 4.2.2 on 2023-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0002_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Não Avaliada', 'Não Avaliada'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada')], default='Não Avaliada'),
        ),
    ]
